### ISSUE TITLE
highway mining flags are memory based

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#107]
Rather than a visible flag that has to be .remove()'d and .create()'d, we should have an array in memory of flags with all the same properties and more. Downside would be that we can't manually interact with them. Upside would be that we wouldn't have to spend intents on placing/removing, we can create/move/remove them without vision of the room, we can manipulate them in ways that regular flags can't be.

These flags could still be manually changed using console commands. We could use roomVisuals to visualize the flags in game. If these flags are easy enough to manipulate, we can replace all other flags with these as well.

**Comment by jordansafer** [comment]
all flags are now invisible and memory based
