### ISSUE TITLE
Mineral mining not necessary

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#108]
Minerals should only be mined if there is a shortage OR the price of the mineral is more than triple the price of energy OR the bucket is full.

**Comment by jordansafer** [comment]
tbh we should just buy if there’s a shortage. if this drives the orice up to 3x energy then we start mining

**Comment by JonathanSafer** [comment]
Agreed. As a side note, we should probably stop trying to arbitrage bars, since that is unlikely to ever be profitable again, especially now that energy prices are relevant (costs energy to make bars).
