### ISSUE TITLE
All creeps should die and not go back

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#115]
power miner should die and not go back, just like dminers. rn if a dminer sees that an enemy owns a room, it will mark it as bad and find another route to the destination. build this into "multi-room move" so all creeps use this strategy.

**Comment by JonathanSafer** [comment]
To translate this into English: power miners should be able to identify hostile rooms, similarly to how dMiners do.

**Comment by jordansafer** [comment]
חבל
