### ISSUE TITLE
room layout

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#133]
a new room layout is needed, partially because of the upcoming new labs, but also to make extension filling more efficient.

**Comment by JonathanSafer** [comment]
Extensions can be more tightly packed in areas where only transporters will walk

**Comment by jordansafer** [comment]
i think transporters also visit labs and other buildings so i’m not sure a change is needed

**Comment by JonathanSafer** [comment]
The point is that locations the *only* need to be accessed by transporters don’t need to have more than one point of contact. At the moment, many of them do
