### ISSUE TITLE
Auto link building

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#16]
Links get auto built 
Link can’t block off source, can’t be on a road, must be adjacent to a spot that miner could stand

**Comment by JonathanSafer** [comment]
Possible strategy:
Find possible miner positions, go through miner positions and find potential link spots for each miner spot. If link spot is legal, place it and break from loop.

**Comment by jordansafer** [comment]
if there is already a link, the room shouldn't build 1. alternatively (don't do this) the planner can destroy the old links

**Comment by jordansafer** [comment]
case study- E11 S9:   W S S W       W = wall, S = source, L = link, C = creep
                      L C C L

**Comment by jordansafer** [comment]
decided not to handle double source caes
