### ISSUE TITLE
Upgrader use links

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#41]
Change upgrader to use links. #16 must be completed first, with a link placed by the controller for the upgrader to use.

**Comment by jordansafer** [comment]
1. If it's optional, base will detect where upgrader link is available?
1. Upgrader body type will be different/need less carry
1. Upgrader will do nothing if no energy is available in the link to upgrade with.

**Comment by Sarge0725** [comment]
Hi there, I am a noob, but this worked for me
` var closestTarget = this.pos.findClosestByPath(FIND_STRUCTURES, {
            filter: (s) => (s.structureType == STRUCTURE_EXTENSION)
s.store.getFreeCapacity(RESOURCE_ENERGY) > 0
`

**Comment by jordansafer** [comment]
@Sarge0725 , why do you use STRUCTURE_EXTENSION when searching for links? We would use something like this for our transporters, which refill extensions
