### ISSUE TITLE
CPU Saving from bucket

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#45]
If we are using over 20 CPU/tick and bucket is running low (under 1k?), skip non-critical tasks. Also a lazy approach to hibernating => randomly choose 10 cities to run each tick (not perfect since cities will still end up doing similar work, it just limits the number of cities doing work per tick).

**Comment by JonathanSafer** [comment]
definitely veto pt 2 of this due to gross energy waste, communication inconsistencies, military effects, missed reactions/ out of sync creep actions etc.

**Comment by JonathanSafer** [comment]
currently when the bucket is low we already: stop placing power mining and deposit mining flags, stop power processing, stop lab reactions, decrease upgrader usage in RCL 8 rooms, stop spawning builders/repairers at RCL8.

**Comment by JonathanSafer** [comment]
additionally we could stop factory usage, and make the transition to dormant mode quick for cities in case of absolute need for CPU
