### ISSUE TITLE
Enhancement#2 - Increase builder count at low rcl

### ISSUE THREAD

**Issue by DragonFire12** [jordansafer/screeps#50]
I like the idea of having that container being built near the spawn,but it would be much better if it was to be built on one of the adjacent squares of the spawn so that allows for recycling creeps but also for storing energy until the storage comes online,also it would help if the number of builders was increased from 1 to 3 or 4 at rcl 1 so the colony develops much faster.

**Comment by DragonFire12** [comment]
to summarise,increase to number of builders from 1 to 3/4 at rcl 1 all the way to 4/5 because from rcl 5 to 8 you can built bigger creeps so 1 builder will do,also build that container near the spawn so it allows for recycling of creeps which no longer have purpose or are near death,the container where is currently placed only has 1 purpose,to store energy but if it was built near the spawn it would also serve a second purpose,to store the energy of recycled creeps

**Comment by jordansafer** [comment]
rn, the storage is also built in the same place as the container (2 squares from the spawn).
- for builders sounds good, i can increase the count to 3. at some point the builders will get in each others way and just create traffic in general, so there are limited returns
- for recycling creeps, are there cases where we need to recycle creeps? we try to use our creeps for their entire lifetimes. there are a few exceptions to this at lower rcls (rcl1/rcl2, occasional defense)

**Comment by DragonFire12** [comment]
recycling defense creeps and maybe some of the creeps that take care of running the labs so they don't die with minerals/boosts on them and they get lost because creeps aren't fast enough at getting them when the grave stone dissapears

**Comment by jordansafer** [comment]
this makes sense. i think we could save the minerals though if the creeps taking care of the labs deposit the minerals before they die, working til the last second

**Comment by DragonFire12** [comment]
guess you're right,but the ways i see it is:better be safe than sorry

**Comment by jordansafer** [comment]
issue to take care of:
- make transporters put energy in storage/container before dying (#53 )

**Comment by DragonFire12** [comment]
and increase the number of builders,yes

**Comment by jordansafer** [comment]
oops, yes, forgot that was this ticket. I'll let #53 track transporters/energy, this ticket can be for increasing builders.
- increase builders to 3 at low rcl

**Comment by DragonFire12** [comment]
yeah,now everything is in order
