### ISSUE TITLE
Repair boost

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#54]
Similar to how upgraders inject themselves with upgrade boost, builders should do so with repair boost (at least at RCL 8)

**Comment by DragonFire12** [comment]
i also think that `injecting` the spawn builders or whatever they're called(the creeps which build a newly claimed room) should be injected with `WORK` part boosts so they get the room up and running faster

**Comment by JonathanSafer** [comment]
Good point.

**Comment by JonathanSafer** [comment]
builders now attempt to boost themselves when possible. rooms do not transfer repair boost yet.
