### ISSUE TITLE
Start walls at RCL 7

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#63]
RCL 7 rooms should start making ramparts at all of the wallspots since RCL 7 is a very vulnerable period. At the RCL 8 transition, the room should start building walls in the necessary positions, and allow the ramparts to decay (this part will involve some work on the builder).

**Comment by JonathanSafer** [comment]
create ramparts at wall spots that are exactly 3 range from the controller to avoid interfering with upgraders

**Comment by jordansafer** [comment]
Is this done?

**Comment by JonathanSafer** [comment]
not the second part, but should be a relatively easy task
