### ISSUE TITLE
rooms tranfer work boost

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#66]
SBs and builders have support to use work boost, but we are missing logic to transfer this from other rooms to labs. Ferries need to supply the new boost. SpawnBuilders can request the boost in advance (when they are scheduled to spawn or even earlier), but ferries need to support the request. Maybe the ferry should have a boost work queue

**Comment by JonathanSafer** [comment]
Can you clarify the role ferries should have in this/ what the issue is? Right now SBs and builders should be doing all of the mineral transferring to boost themselves.

**Comment by jordansafer** [comment]
nm this isn't needed
