### ISSUE TITLE
Quad (high volume creep attack)

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#69]
2 creeps => 20 move parts + 20 tough (should be 12/creep but here 10) + 30 heal => 30 attack/ranged attack/break (useful parts)
3 creeps => 30mv, 30tg, 30 heal, 60 useful parts
4 creeps => 40mv, 40tgh, 30 heal, 90 useful parts. Can easily have extra heal (40?), extra tough (48), still have 72 useful parts => 72 ranged attack, 36 ranged attack + 36 work, etc.

ATK: 120/part. RANGED: 40/part. HEAL: 48/part. DISMANTLE: 200/part.
Tough: 333 health/part.
10 tough = 3333 dmg. 12 tough = 4k dmg (6 towers max at 600 = 3600 dmg * 2 ticks if heals are misdirected on previous tick). 7200 dmg = 22 tough per creep.
Required: 10 moves.
Remaining: 72 parts. 1080 healed is 23 heals.

Alternative is 3600 damage => 75 heals (vs 88 tough + 23 heals = 111)
48 tough + 48 heal + 50 move + 64 ranged attack (or 32 range/32 break)

**Comment by jordansafer** [comment]
group state: spawn -> boost -> group -> move to target (attack etc)
creep state: move to x -> attack x -> boost self (basically all decisions made at the group level)

Path planning: path plan for 1 creep, update cost matrix for room so 2 wide is required

**Comment by JonathanSafer** [comment]
One issue to deal with (mostly for quads but sometimes for the other combos) is that some creeps will spawn early. Once a creep is boosted it can NOT be renewed, so the early spawners will have to find a way to renew themselves until they detect that the whole squad is present. This would be part of the spawn state

**Comment by JonathanSafer** [comment]
once all squad members are spawned, each member should be designated a number (1 - 4).
This will determine their initial alignment position. Creep #1 will determine the rally point (if the squad forms inside of the walls it won't be able to get out).

**Comment by JonathanSafer** [comment]
Once the squad is formed (group state *4*), Creep `1` will do all of the decision making

**Comment by JonathanSafer** [comment]
For motion, use `room.findPath()` method, with the moving creep being the top left position of the quad. The CM can consider every square that is one above or one to the left of a wall to be impassable. Additionally, every tile that is one above or one to the left of a swamp should be updated to the swamp cost since the whole squad will be affected by a swamp as if all of them walked in the swamp.

**Comment by JonathanSafer** [comment]
serialized CM should be cached in global, along with the path

**Comment by JonathanSafer** [comment]
creeps don't move if there is an enemy in a position to break the squad
