### ISSUE TITLE
E11S310: No sources available

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#71]
Scheduled miners spawn and don't know where to go

**Comment by JonathanSafer** [comment]
this may be because the miner respawned itself too soon. Miners should request a respawn at the tick that would cause their replacement to spawn at the same tick that the elder dies.
`creep.ticksToLive == creep.body.length * CREEP_SPAWN_TIME`

**Comment by jordansafer** [comment]
i disagree. if we want to maximize mining efficiency, a miner should spawn early and walk to the source, arriving right when the previous miner dies. since miners don’t mine every tick though, spawning when previous miner dies will be good enough

**Comment by JonathanSafer** [comment]
Okay we can do that too. Miner's can simply filter out other miners that have less than 50 ttl when looking for a source
