### ISSUE TITLE
multiroom path planning v2

### ISSUE THREAD

**Issue by jordansafer** [jordansafer/screeps#89]
v2 multiroom planning:
A. find the closest highway. B. move along highways (minimal path planning). C. Move to the destination.

Calculate long distances by doing distance to highway + 50*highways + distance from the highway, instead of doing any path planning within the highway rooms

**Comment by JonathanSafer** [comment]
I don't think we'll need this anymore with newMove. Can we close this?

**Comment by jordansafer** [comment]
let’s close it, but it is an idea for the future if long distance path planning is a problem for us
